version: '3.8'

services:
  prime-calculator-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prime-calculator-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory if needed
      - ./logs:/app/logs
    networks:
      - prime-network

networks:
  prime-network:
    driver: bridge

# Optional: Add volume for persistent data if needed
volumes:
  app-data:
    driver: local